//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Trez
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfLong", Namespace="http://tempuri.org/", ItemName="long")]
    public class ArrayOfLong : System.Collections.Generic.List<long>
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfInt", Namespace="http://tempuri.org/", ItemName="int")]
    public class ArrayOfInt : System.Collections.Generic.List<int>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Trez.TrezSmsServiceSoap")]
    public interface TrezSmsServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendMessageResponse> SendMessageAsync(Trez.SendMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageWithUDH", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendMessageWithUDHResponse> SendMessageWithUDHAsync(Trez.SendMessageWithUDHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessagesWithUDH", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendMessagesWithUDHResponse> SendMessagesWithUDHAsync(Trez.SendMessagesWithUDHRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMultiMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendMultiMessageResponse> SendMultiMessageAsync(Trez.SendMultiMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendMessageForPhp", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendMessageForPhpResponse> SendMessageForPhpAsync(Trez.SendMessageForPhpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendOneMessageResponse> SendOneMessageAsync(Trez.SendOneMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetMessageStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.GetMessageStatusResponse> GetMessageStatusAsync(Trez.GetMessageStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSchaduleMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendSchaduleMessageResponse> SendSchaduleMessageAsync(Trez.SendSchaduleMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendSchaduleMessageForPhp", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendSchaduleMessageForPhpResponse> SendSchaduleMessageForPhpAsync(Trez.SendSchaduleMessageForPhpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendCourseMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendCourseMessageResponse> SendCourseMessageAsync(Trez.SendCourseMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCredit", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.GetCreditResponse> GetCreditAsync(Trez.GetCreditRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetReciveMessage", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.GetReciveMessageResponse> GetReciveMessageAsync(Trez.GetReciveMessageRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetUnReciveMessageCount", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.GetUnReciveMessageCountResponse> GetUnReciveMessageCountAsync(Trez.GetUnReciveMessageCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SendOneMessageQuickly", ReplyAction="*")]
        System.Threading.Tasks.Task<Trez.SendOneMessageQuicklyResponse> SendOneMessageQuicklyAsync(Trez.SendOneMessageQuicklyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessage", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessageRequestBody Body;
        
        public SendMessageRequest()
        {
        }
        
        public SendMessageRequest(Trez.SendMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Trez.ArrayOfString ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Class;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Trez.ArrayOfLong UserMessageId;
        
        public SendMessageRequestBody()
        {
        }
        
        public SendMessageRequestBody(string Username, string Passwod, string SenderNumebr, string MessageBody, Trez.ArrayOfString ReciptionNumbers, int Class, Trez.ArrayOfLong UserMessageId)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.Class = Class;
            this.UserMessageId = UserMessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessageResponseBody Body;
        
        public SendMessageResponse()
        {
        }
        
        public SendMessageResponse(Trez.SendMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Trez.ArrayOfLong SendMessageResult;
        
        public SendMessageResponseBody()
        {
        }
        
        public SendMessageResponseBody(Trez.ArrayOfLong SendMessageResult)
        {
            this.SendMessageResult = SendMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithUDHRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithUDH", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessageWithUDHRequestBody Body;
        
        public SendMessageWithUDHRequest()
        {
        }
        
        public SendMessageWithUDHRequest(Trez.SendMessageWithUDHRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithUDHRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UDH;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Class;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public long UserMessageId;
        
        public SendMessageWithUDHRequestBody()
        {
        }
        
        public SendMessageWithUDHRequestBody(string Username, string Passwod, string SenderNumebr, string MessageBody, string ReciptionNumbers, string UDH, int Class, long UserMessageId)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.UDH = UDH;
            this.Class = Class;
            this.UserMessageId = UserMessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageWithUDHResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageWithUDHResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessageWithUDHResponseBody Body;
        
        public SendMessageWithUDHResponse()
        {
        }
        
        public SendMessageWithUDHResponse(Trez.SendMessageWithUDHResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageWithUDHResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Trez.ArrayOfLong SendMessageWithUDHResult;
        
        public SendMessageWithUDHResponseBody()
        {
        }
        
        public SendMessageWithUDHResponseBody(Trez.ArrayOfLong SendMessageWithUDHResult)
        {
            this.SendMessageWithUDHResult = SendMessageWithUDHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessagesWithUDHRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessagesWithUDH", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessagesWithUDHRequestBody Body;
        
        public SendMessagesWithUDHRequest()
        {
        }
        
        public SendMessagesWithUDHRequest(Trez.SendMessagesWithUDHRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessagesWithUDHRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Trez.ArrayOfString MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Trez.ArrayOfString ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string UDH;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Class;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public Trez.ArrayOfLong UserMessageId;
        
        public SendMessagesWithUDHRequestBody()
        {
        }
        
        public SendMessagesWithUDHRequestBody(string Username, string Passwod, string SenderNumebr, Trez.ArrayOfString MessageBody, Trez.ArrayOfString ReciptionNumbers, string UDH, int Class, Trez.ArrayOfLong UserMessageId)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.UDH = UDH;
            this.Class = Class;
            this.UserMessageId = UserMessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessagesWithUDHResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessagesWithUDHResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessagesWithUDHResponseBody Body;
        
        public SendMessagesWithUDHResponse()
        {
        }
        
        public SendMessagesWithUDHResponse(Trez.SendMessagesWithUDHResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessagesWithUDHResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Trez.ArrayOfLong SendMessagesWithUDHResult;
        
        public SendMessagesWithUDHResponseBody()
        {
        }
        
        public SendMessagesWithUDHResponseBody(Trez.ArrayOfLong SendMessagesWithUDHResult)
        {
            this.SendMessagesWithUDHResult = SendMessagesWithUDHResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMultiMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMultiMessage", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMultiMessageRequestBody Body;
        
        public SendMultiMessageRequest()
        {
        }
        
        public SendMultiMessageRequest(Trez.SendMultiMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMultiMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Trez.ArrayOfString MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Trez.ArrayOfString ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Class;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public Trez.ArrayOfLong UserMessageId;
        
        public SendMultiMessageRequestBody()
        {
        }
        
        public SendMultiMessageRequestBody(string Username, string Passwod, string SenderNumebr, Trez.ArrayOfString MessageBody, Trez.ArrayOfString ReciptionNumbers, int Class, Trez.ArrayOfLong UserMessageId)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.Class = Class;
            this.UserMessageId = UserMessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMultiMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMultiMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMultiMessageResponseBody Body;
        
        public SendMultiMessageResponse()
        {
        }
        
        public SendMultiMessageResponse(Trez.SendMultiMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMultiMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Trez.ArrayOfLong SendMultiMessageResult;
        
        public SendMultiMessageResponseBody()
        {
        }
        
        public SendMultiMessageResponseBody(Trez.ArrayOfLong SendMultiMessageResult)
        {
            this.SendMultiMessageResult = SendMultiMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageForPhpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageForPhp", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessageForPhpRequestBody Body;
        
        public SendMessageForPhpRequest()
        {
        }
        
        public SendMessageForPhpRequest(Trez.SendMessageForPhpRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageForPhpRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Class;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string UserMessageId;
        
        public SendMessageForPhpRequestBody()
        {
        }
        
        public SendMessageForPhpRequestBody(string Username, string Password, string SenderNumebr, string MessageBody, string ReciptionNumbers, int Class, string UserMessageId)
        {
            this.Username = Username;
            this.Password = Password;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.Class = Class;
            this.UserMessageId = UserMessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMessageForPhpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMessageForPhpResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendMessageForPhpResponseBody Body;
        
        public SendMessageForPhpResponse()
        {
        }
        
        public SendMessageForPhpResponse(Trez.SendMessageForPhpResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendMessageForPhpResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Trez.ArrayOfLong SendMessageForPhpResult;
        
        public SendMessageForPhpResponseBody()
        {
        }
        
        public SendMessageForPhpResponseBody(Trez.ArrayOfLong SendMessageForPhpResult)
        {
            this.SendMessageForPhpResult = SendMessageForPhpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOneMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOneMessage", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendOneMessageRequestBody Body;
        
        public SendOneMessageRequest()
        {
        }
        
        public SendOneMessageRequest(Trez.SendOneMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOneMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Class;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public long UserMessageId;
        
        public SendOneMessageRequestBody()
        {
        }
        
        public SendOneMessageRequestBody(string Username, string Passwod, string SenderNumebr, string MessageBody, string ReciptionNumbers, int Class, long UserMessageId)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.Class = Class;
            this.UserMessageId = UserMessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOneMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOneMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendOneMessageResponseBody Body;
        
        public SendOneMessageResponse()
        {
        }
        
        public SendOneMessageResponse(Trez.SendOneMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOneMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SendOneMessageResult;
        
        public SendOneMessageResponseBody()
        {
        }
        
        public SendOneMessageResponseBody(long SendOneMessageResult)
        {
            this.SendOneMessageResult = SendOneMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatus", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetMessageStatusRequestBody Body;
        
        public GetMessageStatusRequest()
        {
        }
        
        public GetMessageStatusRequest(Trez.GetMessageStatusRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageStatusRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public Trez.ArrayOfLong MessageId;
        
        public GetMessageStatusRequestBody()
        {
        }
        
        public GetMessageStatusRequestBody(string Username, string Passwod, string SenderNumebr, Trez.ArrayOfLong MessageId)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.MessageId = MessageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetMessageStatusResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetMessageStatusResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetMessageStatusResponseBody Body;
        
        public GetMessageStatusResponse()
        {
        }
        
        public GetMessageStatusResponse(Trez.GetMessageStatusResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetMessageStatusResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Trez.ArrayOfInt GetMessageStatusResult;
        
        public GetMessageStatusResponseBody()
        {
        }
        
        public GetMessageStatusResponseBody(Trez.ArrayOfInt GetMessageStatusResult)
        {
            this.GetMessageStatusResult = GetMessageStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSchaduleMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSchaduleMessage", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendSchaduleMessageRequestBody Body;
        
        public SendSchaduleMessageRequest()
        {
        }
        
        public SendSchaduleMessageRequest(Trez.SendSchaduleMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSchaduleMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Trez.ArrayOfString ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime SendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Class;
        
        public SendSchaduleMessageRequestBody()
        {
        }
        
        public SendSchaduleMessageRequestBody(string Username, string Passwod, string SenderNumebr, string MessageBody, Trez.ArrayOfString ReciptionNumbers, System.DateTime SendDate, int Class)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.SendDate = SendDate;
            this.Class = Class;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSchaduleMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSchaduleMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendSchaduleMessageResponseBody Body;
        
        public SendSchaduleMessageResponse()
        {
        }
        
        public SendSchaduleMessageResponse(Trez.SendSchaduleMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSchaduleMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSchaduleMessageResult;
        
        public SendSchaduleMessageResponseBody()
        {
        }
        
        public SendSchaduleMessageResponseBody(string SendSchaduleMessageResult)
        {
            this.SendSchaduleMessageResult = SendSchaduleMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSchaduleMessageForPhpRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSchaduleMessageForPhp", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendSchaduleMessageForPhpRequestBody Body;
        
        public SendSchaduleMessageForPhpRequest()
        {
        }
        
        public SendSchaduleMessageForPhpRequest(Trez.SendSchaduleMessageForPhpRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSchaduleMessageForPhpRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime SendDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int Class;
        
        public SendSchaduleMessageForPhpRequestBody()
        {
        }
        
        public SendSchaduleMessageForPhpRequestBody(string Username, string Password, string SenderNumebr, string MessageBody, string ReciptionNumbers, System.DateTime SendDate, int Class)
        {
            this.Username = Username;
            this.Password = Password;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.SendDate = SendDate;
            this.Class = Class;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendSchaduleMessageForPhpResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendSchaduleMessageForPhpResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendSchaduleMessageForPhpResponseBody Body;
        
        public SendSchaduleMessageForPhpResponse()
        {
        }
        
        public SendSchaduleMessageForPhpResponse(Trez.SendSchaduleMessageForPhpResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendSchaduleMessageForPhpResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendSchaduleMessageForPhpResult;
        
        public SendSchaduleMessageForPhpResponseBody()
        {
        }
        
        public SendSchaduleMessageForPhpResponseBody(string SendSchaduleMessageForPhpResult)
        {
            this.SendSchaduleMessageForPhpResult = SendSchaduleMessageForPhpResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCourseMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCourseMessage", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendCourseMessageRequestBody Body;
        
        public SendCourseMessageRequest()
        {
        }
        
        public SendCourseMessageRequest(Trez.SendCourseMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCourseMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Passwod;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Topic;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public Trez.ArrayOfString ReciptionNumbers;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.DateTime StartDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime EndDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public int Period;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public int Class;
        
        public SendCourseMessageRequestBody()
        {
        }
        
        public SendCourseMessageRequestBody(string Username, string Passwod, string SenderNumebr, string Topic, string MessageBody, Trez.ArrayOfString ReciptionNumbers, System.DateTime StartDate, System.DateTime EndDate, int Period, int Class)
        {
            this.Username = Username;
            this.Passwod = Passwod;
            this.SenderNumebr = SenderNumebr;
            this.Topic = Topic;
            this.MessageBody = MessageBody;
            this.ReciptionNumbers = ReciptionNumbers;
            this.StartDate = StartDate;
            this.EndDate = EndDate;
            this.Period = Period;
            this.Class = Class;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendCourseMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendCourseMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendCourseMessageResponseBody Body;
        
        public SendCourseMessageResponse()
        {
        }
        
        public SendCourseMessageResponse(Trez.SendCourseMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendCourseMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendCourseMessageResult;
        
        public SendCourseMessageResponseBody()
        {
        }
        
        public SendCourseMessageResponseBody(string SendCourseMessageResult)
        {
            this.SendCourseMessageResult = SendCourseMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCredit", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetCreditRequestBody Body;
        
        public GetCreditRequest()
        {
        }
        
        public GetCreditRequest(Trez.GetCreditRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumber;
        
        public GetCreditRequestBody()
        {
        }
        
        public GetCreditRequestBody(string Username, string Password, string SenderNumber)
        {
            this.Username = Username;
            this.Password = Password;
            this.SenderNumber = SenderNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCreditResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCreditResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetCreditResponseBody Body;
        
        public GetCreditResponse()
        {
        }
        
        public GetCreditResponse(Trez.GetCreditResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCreditResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long GetCreditResult;
        
        public GetCreditResponseBody()
        {
        }
        
        public GetCreditResponseBody(long GetCreditResult)
        {
            this.GetCreditResult = GetCreditResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReciveMessageRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReciveMessage", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetReciveMessageRequestBody Body;
        
        public GetReciveMessageRequest()
        {
        }
        
        public GetReciveMessageRequest(Trez.GetReciveMessageRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReciveMessageRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumber;
        
        public GetReciveMessageRequestBody()
        {
        }
        
        public GetReciveMessageRequestBody(string Username, string Password, string SenderNumber)
        {
            this.Username = Username;
            this.Password = Password;
            this.SenderNumber = SenderNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetReciveMessageResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetReciveMessageResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetReciveMessageResponseBody Body;
        
        public GetReciveMessageResponse()
        {
        }
        
        public GetReciveMessageResponse(Trez.GetReciveMessageResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetReciveMessageResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetReciveMessageResult;
        
        public GetReciveMessageResponseBody()
        {
        }
        
        public GetReciveMessageResponseBody(string GetReciveMessageResult)
        {
            this.GetReciveMessageResult = GetReciveMessageResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnReciveMessageCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnReciveMessageCount", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetUnReciveMessageCountRequestBody Body;
        
        public GetUnReciveMessageCountRequest()
        {
        }
        
        public GetUnReciveMessageCountRequest(Trez.GetUnReciveMessageCountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUnReciveMessageCountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumber;
        
        public GetUnReciveMessageCountRequestBody()
        {
        }
        
        public GetUnReciveMessageCountRequestBody(string Username, string Password, string SenderNumber)
        {
            this.Username = Username;
            this.Password = Password;
            this.SenderNumber = SenderNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetUnReciveMessageCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetUnReciveMessageCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.GetUnReciveMessageCountResponseBody Body;
        
        public GetUnReciveMessageCountResponse()
        {
        }
        
        public GetUnReciveMessageCountResponse(Trez.GetUnReciveMessageCountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetUnReciveMessageCountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetUnReciveMessageCountResult;
        
        public GetUnReciveMessageCountResponseBody()
        {
        }
        
        public GetUnReciveMessageCountResponseBody(int GetUnReciveMessageCountResult)
        {
            this.GetUnReciveMessageCountResult = GetUnReciveMessageCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOneMessageQuicklyRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOneMessageQuickly", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendOneMessageQuicklyRequestBody Body;
        
        public SendOneMessageQuicklyRequest()
        {
        }
        
        public SendOneMessageQuicklyRequest(Trez.SendOneMessageQuicklyRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOneMessageQuicklyRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SenderNumebr;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string MessageBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string ReciptionNumber;
        
        public SendOneMessageQuicklyRequestBody()
        {
        }
        
        public SendOneMessageQuicklyRequestBody(string Username, string Password, string SenderNumebr, string MessageBody, string ReciptionNumber)
        {
            this.Username = Username;
            this.Password = Password;
            this.SenderNumebr = SenderNumebr;
            this.MessageBody = MessageBody;
            this.ReciptionNumber = ReciptionNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendOneMessageQuicklyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendOneMessageQuicklyResponse", Namespace="http://tempuri.org/", Order=0)]
        public Trez.SendOneMessageQuicklyResponseBody Body;
        
        public SendOneMessageQuicklyResponse()
        {
        }
        
        public SendOneMessageQuicklyResponse(Trez.SendOneMessageQuicklyResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SendOneMessageQuicklyResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long SendOneMessageQuicklyResult;
        
        public SendOneMessageQuicklyResponseBody()
        {
        }
        
        public SendOneMessageQuicklyResponseBody(long SendOneMessageQuicklyResult)
        {
            this.SendOneMessageQuicklyResult = SendOneMessageQuicklyResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public interface TrezSmsServiceSoapChannel : Trez.TrezSmsServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30514-0828")]
    public partial class TrezSmsServiceSoapClient : System.ServiceModel.ClientBase<Trez.TrezSmsServiceSoap>, Trez.TrezSmsServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TrezSmsServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TrezSmsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), TrezSmsServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrezSmsServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TrezSmsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrezSmsServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TrezSmsServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TrezSmsServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendMessageResponse> Trez.TrezSmsServiceSoap.SendMessageAsync(Trez.SendMessageRequest request)
        {
            return base.Channel.SendMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendMessageResponse> SendMessageAsync(string Username, string Passwod, string SenderNumebr, string MessageBody, Trez.ArrayOfString ReciptionNumbers, int Class, Trez.ArrayOfLong UserMessageId)
        {
            Trez.SendMessageRequest inValue = new Trez.SendMessageRequest();
            inValue.Body = new Trez.SendMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.Class = Class;
            inValue.Body.UserMessageId = UserMessageId;
            return ((Trez.TrezSmsServiceSoap)(this)).SendMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendMessageWithUDHResponse> Trez.TrezSmsServiceSoap.SendMessageWithUDHAsync(Trez.SendMessageWithUDHRequest request)
        {
            return base.Channel.SendMessageWithUDHAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendMessageWithUDHResponse> SendMessageWithUDHAsync(string Username, string Passwod, string SenderNumebr, string MessageBody, string ReciptionNumbers, string UDH, int Class, long UserMessageId)
        {
            Trez.SendMessageWithUDHRequest inValue = new Trez.SendMessageWithUDHRequest();
            inValue.Body = new Trez.SendMessageWithUDHRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.UDH = UDH;
            inValue.Body.Class = Class;
            inValue.Body.UserMessageId = UserMessageId;
            return ((Trez.TrezSmsServiceSoap)(this)).SendMessageWithUDHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendMessagesWithUDHResponse> Trez.TrezSmsServiceSoap.SendMessagesWithUDHAsync(Trez.SendMessagesWithUDHRequest request)
        {
            return base.Channel.SendMessagesWithUDHAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendMessagesWithUDHResponse> SendMessagesWithUDHAsync(string Username, string Passwod, string SenderNumebr, Trez.ArrayOfString MessageBody, Trez.ArrayOfString ReciptionNumbers, string UDH, int Class, Trez.ArrayOfLong UserMessageId)
        {
            Trez.SendMessagesWithUDHRequest inValue = new Trez.SendMessagesWithUDHRequest();
            inValue.Body = new Trez.SendMessagesWithUDHRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.UDH = UDH;
            inValue.Body.Class = Class;
            inValue.Body.UserMessageId = UserMessageId;
            return ((Trez.TrezSmsServiceSoap)(this)).SendMessagesWithUDHAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendMultiMessageResponse> Trez.TrezSmsServiceSoap.SendMultiMessageAsync(Trez.SendMultiMessageRequest request)
        {
            return base.Channel.SendMultiMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendMultiMessageResponse> SendMultiMessageAsync(string Username, string Passwod, string SenderNumebr, Trez.ArrayOfString MessageBody, Trez.ArrayOfString ReciptionNumbers, int Class, Trez.ArrayOfLong UserMessageId)
        {
            Trez.SendMultiMessageRequest inValue = new Trez.SendMultiMessageRequest();
            inValue.Body = new Trez.SendMultiMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.Class = Class;
            inValue.Body.UserMessageId = UserMessageId;
            return ((Trez.TrezSmsServiceSoap)(this)).SendMultiMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendMessageForPhpResponse> Trez.TrezSmsServiceSoap.SendMessageForPhpAsync(Trez.SendMessageForPhpRequest request)
        {
            return base.Channel.SendMessageForPhpAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendMessageForPhpResponse> SendMessageForPhpAsync(string Username, string Password, string SenderNumebr, string MessageBody, string ReciptionNumbers, int Class, string UserMessageId)
        {
            Trez.SendMessageForPhpRequest inValue = new Trez.SendMessageForPhpRequest();
            inValue.Body = new Trez.SendMessageForPhpRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.Class = Class;
            inValue.Body.UserMessageId = UserMessageId;
            return ((Trez.TrezSmsServiceSoap)(this)).SendMessageForPhpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendOneMessageResponse> Trez.TrezSmsServiceSoap.SendOneMessageAsync(Trez.SendOneMessageRequest request)
        {
            return base.Channel.SendOneMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendOneMessageResponse> SendOneMessageAsync(string Username, string Passwod, string SenderNumebr, string MessageBody, string ReciptionNumbers, int Class, long UserMessageId)
        {
            Trez.SendOneMessageRequest inValue = new Trez.SendOneMessageRequest();
            inValue.Body = new Trez.SendOneMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.Class = Class;
            inValue.Body.UserMessageId = UserMessageId;
            return ((Trez.TrezSmsServiceSoap)(this)).SendOneMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.GetMessageStatusResponse> Trez.TrezSmsServiceSoap.GetMessageStatusAsync(Trez.GetMessageStatusRequest request)
        {
            return base.Channel.GetMessageStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.GetMessageStatusResponse> GetMessageStatusAsync(string Username, string Passwod, string SenderNumebr, Trez.ArrayOfLong MessageId)
        {
            Trez.GetMessageStatusRequest inValue = new Trez.GetMessageStatusRequest();
            inValue.Body = new Trez.GetMessageStatusRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageId = MessageId;
            return ((Trez.TrezSmsServiceSoap)(this)).GetMessageStatusAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendSchaduleMessageResponse> Trez.TrezSmsServiceSoap.SendSchaduleMessageAsync(Trez.SendSchaduleMessageRequest request)
        {
            return base.Channel.SendSchaduleMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendSchaduleMessageResponse> SendSchaduleMessageAsync(string Username, string Passwod, string SenderNumebr, string MessageBody, Trez.ArrayOfString ReciptionNumbers, System.DateTime SendDate, int Class)
        {
            Trez.SendSchaduleMessageRequest inValue = new Trez.SendSchaduleMessageRequest();
            inValue.Body = new Trez.SendSchaduleMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.SendDate = SendDate;
            inValue.Body.Class = Class;
            return ((Trez.TrezSmsServiceSoap)(this)).SendSchaduleMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendSchaduleMessageForPhpResponse> Trez.TrezSmsServiceSoap.SendSchaduleMessageForPhpAsync(Trez.SendSchaduleMessageForPhpRequest request)
        {
            return base.Channel.SendSchaduleMessageForPhpAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendSchaduleMessageForPhpResponse> SendSchaduleMessageForPhpAsync(string Username, string Password, string SenderNumebr, string MessageBody, string ReciptionNumbers, System.DateTime SendDate, int Class)
        {
            Trez.SendSchaduleMessageForPhpRequest inValue = new Trez.SendSchaduleMessageForPhpRequest();
            inValue.Body = new Trez.SendSchaduleMessageForPhpRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.SendDate = SendDate;
            inValue.Body.Class = Class;
            return ((Trez.TrezSmsServiceSoap)(this)).SendSchaduleMessageForPhpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendCourseMessageResponse> Trez.TrezSmsServiceSoap.SendCourseMessageAsync(Trez.SendCourseMessageRequest request)
        {
            return base.Channel.SendCourseMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendCourseMessageResponse> SendCourseMessageAsync(string Username, string Passwod, string SenderNumebr, string Topic, string MessageBody, Trez.ArrayOfString ReciptionNumbers, System.DateTime StartDate, System.DateTime EndDate, int Period, int Class)
        {
            Trez.SendCourseMessageRequest inValue = new Trez.SendCourseMessageRequest();
            inValue.Body = new Trez.SendCourseMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Passwod = Passwod;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.Topic = Topic;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumbers = ReciptionNumbers;
            inValue.Body.StartDate = StartDate;
            inValue.Body.EndDate = EndDate;
            inValue.Body.Period = Period;
            inValue.Body.Class = Class;
            return ((Trez.TrezSmsServiceSoap)(this)).SendCourseMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.GetCreditResponse> Trez.TrezSmsServiceSoap.GetCreditAsync(Trez.GetCreditRequest request)
        {
            return base.Channel.GetCreditAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.GetCreditResponse> GetCreditAsync(string Username, string Password, string SenderNumber)
        {
            Trez.GetCreditRequest inValue = new Trez.GetCreditRequest();
            inValue.Body = new Trez.GetCreditRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SenderNumber = SenderNumber;
            return ((Trez.TrezSmsServiceSoap)(this)).GetCreditAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.GetReciveMessageResponse> Trez.TrezSmsServiceSoap.GetReciveMessageAsync(Trez.GetReciveMessageRequest request)
        {
            return base.Channel.GetReciveMessageAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.GetReciveMessageResponse> GetReciveMessageAsync(string Username, string Password, string SenderNumber)
        {
            Trez.GetReciveMessageRequest inValue = new Trez.GetReciveMessageRequest();
            inValue.Body = new Trez.GetReciveMessageRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SenderNumber = SenderNumber;
            return ((Trez.TrezSmsServiceSoap)(this)).GetReciveMessageAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.GetUnReciveMessageCountResponse> Trez.TrezSmsServiceSoap.GetUnReciveMessageCountAsync(Trez.GetUnReciveMessageCountRequest request)
        {
            return base.Channel.GetUnReciveMessageCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.GetUnReciveMessageCountResponse> GetUnReciveMessageCountAsync(string Username, string Password, string SenderNumber)
        {
            Trez.GetUnReciveMessageCountRequest inValue = new Trez.GetUnReciveMessageCountRequest();
            inValue.Body = new Trez.GetUnReciveMessageCountRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SenderNumber = SenderNumber;
            return ((Trez.TrezSmsServiceSoap)(this)).GetUnReciveMessageCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Trez.SendOneMessageQuicklyResponse> Trez.TrezSmsServiceSoap.SendOneMessageQuicklyAsync(Trez.SendOneMessageQuicklyRequest request)
        {
            return base.Channel.SendOneMessageQuicklyAsync(request);
        }
        
        public System.Threading.Tasks.Task<Trez.SendOneMessageQuicklyResponse> SendOneMessageQuicklyAsync(string Username, string Password, string SenderNumebr, string MessageBody, string ReciptionNumber)
        {
            Trez.SendOneMessageQuicklyRequest inValue = new Trez.SendOneMessageQuicklyRequest();
            inValue.Body = new Trez.SendOneMessageQuicklyRequestBody();
            inValue.Body.Username = Username;
            inValue.Body.Password = Password;
            inValue.Body.SenderNumebr = SenderNumebr;
            inValue.Body.MessageBody = MessageBody;
            inValue.Body.ReciptionNumber = ReciptionNumber;
            return ((Trez.TrezSmsServiceSoap)(this)).SendOneMessageQuicklyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrezSmsServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TrezSmsServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TrezSmsServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://sms.trez.ir/TrezSmsService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TrezSmsServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://sms.trez.ir/TrezSmsService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TrezSmsServiceSoap,
            
            TrezSmsServiceSoap12,
        }
    }
}
